import hashlib
import secrets
from dataclasses import dataclass
from fastecdsa.curve import secp256k1
from fastecdsa.point import Point

@dataclass
class RingSignature:
    c0: int
    s: list[int]

class AnonymousRingAuth:
    """Spontaneous Anonymous Group (SAG) Ring Signature for Anonymous Cluster Authentication.
    
    Allows an authorized cluster agent to prove membership and authorization
    without disclosing their static public key or identity slot.
    """
    def __init__(self):
        self.curve = secp256k1
        self.G = secp256k1.G
        self.q = secp256k1.q

    def _hash_challenge(self, msg: bytes, ring: list[Point], L: Point) -> int:
        ring_bytes = b"".join(p.x.to_bytes(32, "big") + p.y.to_bytes(32, "big") for p in ring)
        raw = msg + ring_bytes + L.x.to_bytes(32, "big") + L.y.to_bytes(32, "big")
        return int.from_bytes(hashlib.sha256(raw).digest(), "big") % self.q

    def sign(self, msg: bytes, ring: list[Point], signer_sk: int) -> RingSignature:
        """Generates a ring signature over the authorized cluster public keys."""
        signer_pk = signer_sk * self.G
        if signer_pk not in ring:
            raise ValueError("Signer public key is not in the authorized cluster ring.")

        signer_idx = ring.index(signer_pk)
        n = len(ring)
        alpha = secrets.randbelow(self.q - 1) + 1
        L_pi = alpha * self.G

        c = [0] * n
        s = [0] * n

        # Next challenge in cycle
        c[(signer_idx + 1) % n] = self._hash_challenge(msg, ring, L_pi)
        idx = (signer_idx + 1) % n

        while idx != signer_idx:
            s[idx] = secrets.randbelow(self.q - 1) + 1
            L_i = (s[idx] * self.G) + (c[idx] * ring[idx])
            next_idx = (idx + 1) % n
            c[next_idx] = self._hash_challenge(msg, ring, L_i)
            idx = next_idx

        # Close the ring equation: alpha * G = s_pi * G + c_pi * PK_pi
        s[signer_idx] = (alpha - c[signer_idx] * signer_sk) % self.q
        return RingSignature(c0=c[0], s=s)

    def verify(self, msg: bytes, ring: list[Point], signature: RingSignature) -> bool:
        """Verifies that the signature was generated by a member of the ring without revealing who."""
        n = len(ring)
        if len(signature.s) != n:
            return False

        c = signature.c0
        for i in range(n):
            L_i = (signature.s[i] * self.G) + (c * ring[i])
            c = self._hash_challenge(msg, ring, L_i)

        return c == signature.c0
